name: isdin

networks:
  isdin-network:
    name: isdin-network
    driver: bridge

services:
  microservice:
    container_name: microservice
    command: ["sh", "-c", "npm run start:dev"] # ? This will run the start:dev script defined in package.json, which watches for file changes and restarts the server automatically
    env_file:
      - src/config/environments/.env.development
    volumes:
      - .:/app # ? This will mount the current directory into the container. This allows for hot-reloading
    environment:
      - KAFKA_HOST=kafka
      - RDB_HOST=rdb
    networks:
      - isdin-network
    depends_on:
      - rdb
      - kafka

  rdb:
    container_name: rdb
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aleix
      POSTGRES_PASSWORD: Aleix2024
      POSTGRES_DB: isdin
    networks:
      isdin-network:
        aliases:
          - rdb

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper
    networks:
      isdin-network:
        aliases:
          - zookeeper

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      isdin-network:
        aliases:
          - kafka
    depends_on:
      - zookeeper

