name: isdin
networks:
  isdin-network:
    name: isdin-network
    driver: bridge

services:
  microservice:
    container_name: microservice
    env_file:
      - src/config/environments/.env.production
    environment:
      - RDB_HOST=rdb
      - KAFKA_HOST=kafka
    networks:
      - isdin-network
    depends_on:
      - rdb
      - kafka

  rdb:
    container_name: rdb
    image: postgres
    environment:
      POSTGRES_USER: aleix
      POSTGRES_PASSWORD: Aleix2024
      POSTGRES_DB: isdin
    ports:
      - "5432:5432"
    networks:
      - isdin-network

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper
    networks:
      - isdin-network

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    environment:
      # KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      # KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092,PLAINTEXT_IP://
      # KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    hostname: kafka
    networks:
      - isdin-network
    depends_on:
      - zookeeper

